### ISSUE TITLE
Feature request: Adding logger functionality

### ISSUE THREAD

**Issue by matiasandina** [mike-huls/py-console#1]
I think adding minimal logger functionality would be a cherry on top of this nice package. 

Even the minimal 

```
console.setLoggerFile("path_to_log.whatever", mode = "append/overwrite")
```
That just dumps whatever gets printed by `console` would be a major win for scripts that run for a bunch of time. I find myself wanting to save all the nice printing I do using the package.

**Comment by mike-huls** [comment]
Hello @matiasandina I've added this feature using the built-in logging module. YOu can set the console to log to a file like below:

```
console.setLoggingPath(
            path='test.log',
            when='d',
            interval=1,
            backup_count=1
)
```

The setup above will keep 1 backup and rotate the logfile every 1 (interval) day ('d').
This is to make sure your log files don't get too big. More information on this [here](https://medium.com/towardsdev/my-logging-file-gets-too-big-python-logging-to-multiple-files-c7fccf97d3a4) 

let me know what you think about it!

Kind regards,


Mike

**Comment by matiasandina** [comment]
Hi, 
This looks awesome. I think I'm having some issues with the folder structure on the new install. I installed via pip and tried a different import combinations, but nothing seemed to work. Looks like the `src` directory is not getting created in the pip installation.

```
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import py_console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matias/.local/lib/python3.10/site-packages/py_console/__init__.py", line 1, in <module>
    from src.py_console.console import Console
ModuleNotFoundError: No module named 'src'
>>> from src.py_console.console import Console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'src'
>>> from src.py_console import console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'src'
>>> from py_console.src.py_console import console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matias/.local/lib/python3.10/site-packages/py_console/__init__.py", line 1, in <module>
    from src.py_console.console import Console
ModuleNotFoundError: No module named 'src'
>>> from py_console.py_console import console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matias/.local/lib/python3.10/site-packages/py_console/__init__.py", line 1, in <module>
    from src.py_console.console import Console
ModuleNotFoundError: No module named 'src'
>>> from py_console import src.py_console.console
  File "<stdin>", line 1
    from py_console import src.py_console.console
                              ^
SyntaxError: invalid syntax
>>> from py_console.src import py_console.console
  File "<stdin>", line 1
    from py_console.src import py_console.console
                                         ^
SyntaxError: invalid syntax
>>> from py_console.src import py_console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matias/.local/lib/python3.10/site-packages/py_console/__init__.py", line 1, in <module>
    from src.py_console.console import Console
ModuleNotFoundError: No module named 'src'
>>> from py_console.src.py_console import * 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matias/.local/lib/python3.10/site-packages/py_console/__init__.py", line 1, in <module>
    from src.py_console.console import Console
ModuleNotFoundError: No module named 'src'

```
When I list the directory of my python packages I get:

```
ls /home/matias/.local/lib/python3.10/site-packages/py_console/
console.py  definitions.py  __init__.py  __pycache__
```

**Comment by mike-huls** [comment]
Hi Matias, yes, this was due to me upgrading from setup.py to pyproject.toml. My approach requires all package data to be in the src folder but refactoring also messed up all imports. I've fixed it in the newest version (`0.1.6`).
Let me know if everything works now

**Comment by matiasandina** [comment]
Have not extensively tested on my end (meaning over days and limits), but it's working nicely for my minimal purpose so far. Will update if I find anything odd. Thanks for the new functionality!

**Comment by mike-huls** [comment]
ill close for now.
